const TYPES_EVENTS = [
  'Taxi',
  'Bus',
  'Train',
  'Ship',
  'Drive',
  'Flight',
  'Check-in',
  'Sightseeing',
  'Restaurant',
];

const MSEC_IN_SEC = 1000;
const SEC_IN_MIN = 60;
const MIN_IN_HOUR = 60;
const HOUR_IN_DAY = 24;

const MSEC_IN_HOUR = MIN_IN_HOUR * SEC_IN_MIN * MSEC_IN_SEC;
const MSEC_IN_DAY = HOUR_IN_DAY * MSEC_IN_HOUR;

const SHORT_DATE_TEMPLATE = 'MMM DD';
const TIME_TEMPLATE = 'HH:mm';
const LONG_EVENT_DURATION_TEMPLATE = 'DD[D] HH[H] mm[M]';
const AVERAGE_EVENT_DURATION_TEMPLATE = 'HH[H] mm[M]';
const SHORT_EVENT_DURATION_TEMPLATE = 'mm[M]';
const DATE_EVENT_TEMPLATE = 'DD/MM/YY hh:mm';

export {
  TYPES_EVENTS,
  SHORT_DATE_TEMPLATE,
  DATE_EVENT_TEMPLATE,
  TIME_TEMPLATE,
  LONG_EVENT_DURATION_TEMPLATE,
  AVERAGE_EVENT_DURATION_TEMPLATE,
  SHORT_EVENT_DURATION_TEMPLATE,
  MSEC_IN_DAY,
  MSEC_IN_HOUR,
};
